export const annualChapters = [
  {
    year: "2024 / 25",
    age: 14,
    kicker: "县体育场 · 暴雨中的最后一场选拔",
    title: "球探只带走一个孩子",
    story:
      "省城青训的球探坐在看台上，你的父亲却刚刚失业。入选意味着全家借钱供你离家；留下，则可以继续读书并帮家里照顾小店。",
    choices: [
      {
        eyebrow: "孤注一掷",
        title: "踢一场只属于自己的比赛",
        copy: "不再传安全球，用每一次触球逼球探记住你。",
        impact: "能力 ↑↑ · 信任 ↓",
        effects: { ovr: 4, trust: -7, reputation: 9, goals: 2, value: 12 },
        note: "你完成帽子戏法，队友却在终场后绕开了你。球探递来一张去省城的车票。",
      },
      {
        eyebrow: "让家人安心",
        title: "放弃试训名额",
        copy: "足球可以再等一年，家里的账单不能。",
        impact: "信任 ↑↑↑ · 成长放缓",
        effects: { trust: 16, morale: 7, ovr: 1, assists: 2, value: 3 },
        note: "你回到小店搬货，每晚关门后独自在路灯下练到十一点。",
      },
      {
        eyebrow: "改变条件",
        title: "当面向球探争取全额奖学金",
        copy: "坦白家境，也把选择权重新放回自己手里。",
        impact: "名气 ↑ · 压力 ↑↑",
        effects: { reputation: 12, trust: 8, morale: -4, ovr: 2, value: 8 },
        note: "球探答应承担食宿，但要求你三个月内进入首发，否则立刻回家。",
      },
    ],
  },
  {
    year: "2025 / 26",
    age: 15,
    kicker: "宿舍熄灯后 · 一封匿名邮件",
    title: "有人说你改过年龄",
    story:
      "竞争对手的家长向足协举报你年龄造假，青训资格被临时冻结。教练暗示，只要你别追究消息来源，俱乐部可以悄悄把事情压下去。",
    choices: [
      {
        eyebrow: "正面迎战",
        title: "公开出生证明并要求调查",
        copy: "清白不该靠俱乐部私下施舍。",
        impact: "名气 ↑↑ · 信任 ↓",
        effects: { reputation: 16, trust: -5, morale: 8, ovr: 2, apps: 3, value: 15 },
        note: "你洗清嫌疑，也查出举报来自队友家长。那名队友第二天被所有人孤立。",
      },
      {
        eyebrow: "保护队友",
        title: "接受内部和解",
        copy: "让事情停在更衣室，不毁掉另一个孩子。",
        impact: "信任 ↑↑ · 名气 ↓",
        effects: { trust: 17, reputation: -4, morale: 4, apps: 5, assists: 2, value: 10 },
        note: "资格恢复了，但网络上的怀疑从未完全消失。那名队友欠了你一辈子的人情。",
      },
      {
        eyebrow: "离开是非地",
        title: "申请转投另一家青训",
        copy: "用下一场德比回答所有传言。",
        impact: "能力 ↑↑ · 仇恨 ↑↑",
        effects: { ovr: 4, reputation: 12, trust: -10, apps: 6, goals: 4, value: 22 },
        note: "德比第 90 分钟，你绝杀旧主。看台上同时响起欢呼和辱骂。",
      },
    ],
  },
  {
    year: "2026 / 27",
    age: 16,
    kicker: "青训淘汰日 · 最后十分钟",
    title: "名单只剩一个位置",
    story:
      "你和室友竞争同一份职业合同。比分 1:1，教练说谁能改变比赛谁就留下。室友低声说，他家里已经借钱搬到了这座城市。",
    choices: [
      {
        eyebrow: "赢家逻辑",
        title: "抢走最后一次射门",
        copy: "你的位置更好，但这一脚本该由他完成。",
        impact: "名气 ↑↑ · 信任 ↓",
        effects: { ovr: 3, trust: -8, reputation: 11, apps: 4, goals: 3, value: 35 },
        note: "球进了，你留下。室友当晚收拾行李，没有和你告别。",
      },
      {
        eyebrow: "共同命运",
        title: "把绝杀传给室友",
        copy: "让他被看见，也赌教练愿意留下你们两个。",
        impact: "信任 ↑↑↑ · 身价风险",
        effects: { ovr: 2, trust: 16, morale: 9, apps: 4, assists: 3, value: 18 },
        note: "他罚进绝杀。你留下，他被另一家球队带走——临行前紧紧抱住了你。",
      },
      {
        eyebrow: "拒绝剧本",
        title: "赛后质问教练",
        copy: "把两个孩子逼成敌人，不该叫竞争。",
        impact: "名气 ↑ · 信任 ↓↓",
        effects: { ovr: 2, trust: -14, reputation: 15, morale: 6, apps: 2, value: 20 },
        note: "视频流出后引发争论。俱乐部留下了你，也把你标成了“不好管理”。",
      },
    ],
  },
  {
    year: "2027 / 28",
    age: 17,
    kicker: "训练基地外 · 父亲等了一夜",
    title: "高考，还是职业合同",
    story:
      "俱乐部要求你立刻停学，签一份没有出场承诺的学徒合同。父亲把大学报名表推到你面前：家里撑不起第二次失败。",
    choices: [
      {
        eyebrow: "孤注一掷",
        title: "撕掉报名表",
        copy: "把所有退路留在基地门外。",
        impact: "能力 ↑↑ · 家庭关系 ↓",
        effects: { ovr: 4, energy: -5, morale: 5, trust: 4, apps: 8, goals: 3, value: 40 },
        note: "父亲三个月没接你的电话。你成为梯队里最早到、最晚走的人。",
      },
      {
        eyebrow: "双线作战",
        title: "白天训练，深夜备考",
        copy: "谁说人生只能押一边。",
        impact: "体能 ↓↓ · 信任 ↑",
        effects: { ovr: 2, energy: -16, trust: 8, morale: 4, apps: 6, assists: 2, value: 28 },
        note: "你低分擦线拿到录取通知，也没有缺席一次训练。",
      },
      {
        eyebrow: "暂时离场",
        title: "先去读大学",
        copy: "保留学籍，在校园联赛等待下一次机会。",
        impact: "士气 ↑ · 身价增长慢",
        effects: { ovr: 1, morale: 12, reputation: 5, apps: 12, goals: 5, assists: 4, value: 18 },
        note: "俱乐部撤回合同。半年后，你在大学杯决赛的帽子戏法又把球探引回看台。",
      },
    ],
  },
  {
    year: "2028 / 29",
    age: 18,
    kicker: "成年礼 · 三份合同",
    title: "经纪人说：别只看钱",
    story:
      "本地球队保证首发，国内豪门给三倍工资但不保证报名，海外低级别球队只报销一张单程票。三份合同都在今晚失效。",
    choices: [
      {
        eyebrow: "稳定出场",
        title: "接受稳定出场合同",
        copy: "小舞台，但每一分钟都属于你。",
        impact: "出场 ↑↑↑ · 身价 ↑",
        effects: { ovr: 3, apps: 27, goals: 9, assists: 7, value: 150, trust: 8 },
        note: "你穿上 27 号球衣，从首发名单最底端开始了职业生涯。",
      },
      {
        eyebrow: "豪门赌桌",
        title: "接受豪门轮换合同",
        copy: "工资翻倍，也可能整年坐在看台。",
        impact: "能力 ↑↑ · 士气风险",
        effects: { ovr: 5, morale: -7, apps: 11, goals: 3, assists: 3, value: 210, reputation: 8 },
        note: "你第一次见到数据实验室，也第一次连续十二场没有进入名单。",
      },
      {
        eyebrow: "单程票",
        title: "接受海外联赛合同",
        copy: "陌生语言、半职业联赛，没有回程。",
        impact: "能力 ↑ · 名气 ↑↑",
        effects: { ovr: 4, energy: -7, reputation: 15, apps: 31, goals: 12, assists: 6, value: 180 },
        note: "第一个冬天你住在洗衣房楼上。春天来时，全城已经会念你的名字。",
      },
    ],
  },
  {
    year: "2029 / 30",
    age: 19,
    kicker: "职业更衣室 · 欢迎仪式",
    title: "队长让你跪着唱队歌",
    story:
      "老队员们堵住出口，把手机镜头对准你。有人说这只是传统，有人把一瓶酒塞进你手里。偷拍视频正在直播。",
    choices: [
      {
        eyebrow: "吞下去",
        title: "照做，换取接纳",
        copy: "今晚难堪，总比整个赛季被孤立好。",
        impact: "信任 ↑ · 士气 ↓↓",
        effects: { trust: 10, morale: -15, apps: 23, goals: 7, assists: 5, value: 80 },
        note: "更衣室接纳了你。每当新人到来，你却开始厌恶镜子里的自己。",
      },
      {
        eyebrow: "当场反击",
        title: "夺过手机，退出直播",
        copy: "拒绝配合，也不给任何人制造流量。",
        impact: "士气 ↑↑ · 信任 ↓",
        effects: { morale: 14, trust: -7, reputation: 8, apps: 20, goals: 6, assists: 5, value: 85 },
        note: "视频只留下十秒，却足够让外界站队。队长从此不再叫你的名字。",
      },
      {
        eyebrow: "留下证据",
        title: "笑着配合，赛后举报",
        copy: "让纪律委员会处理所谓的传统。",
        impact: "名气 ↑↑ · 更衣室分裂",
        effects: { trust: -18, reputation: 20, morale: 5, apps: 14, assists: 6, value: 100 },
        note: "三名老将被禁赛。更衣室安静了，你的衣柜却连续一个月被泼水。",
      },
    ],
  },
  {
    year: "2030 / 31",
    age: 20,
    kicker: "国青队报到前夜",
    title: "脚踝里有一条裂缝",
    story:
      "这是你第一次入选国字号，也是海外球探集中出现的锦标赛。队医说继续踢可能让伤势恶化，主教练却问你能不能坚持三场。",
    choices: [
      {
        eyebrow: "带伤出征",
        title: "封闭针，首发",
        copy: "这种机会可能一生只有一次。",
        impact: "名气 ↑↑ · 体能 ↓↓↓",
        effects: { ovr: 2, energy: -22, reputation: 18, apps: 24, goals: 8, assists: 6, value: 160 },
        note: "你打进两球，国青队晋级。庆祝时，你已经无法靠自己走回更衣室。",
      },
      {
        eyebrow: "保护未来",
        title: "退出名单，接受治疗",
        copy: "错过国字号首秀，保住下一份合同。",
        impact: "体能 ↑↑↑ · 名气 ↓",
        effects: { energy: 19, morale: -8, reputation: -5, apps: 16, goals: 4, value: 55 },
        note: "国青队止步小组赛。半年后，你重新完整地跑了九十分钟。",
      },
      {
        eyebrow: "精确下注",
        title: "只踢淘汰赛二十分钟",
        copy: "要求把出场上限写进医疗协议。",
        impact: "信任 ↑↑ · 能力 ↑",
        effects: { ovr: 3, energy: -7, trust: 12, apps: 19, goals: 5, assists: 8, value: 105 },
        note: "你在八强战送出致命助攻。教练第一次允许球员参与决定风险。",
      },
    ],
  },
  {
    year: "2031 / 32",
    age: 21,
    kicker: "杯赛决赛 · 第 93 分钟",
    title: "点球点前，两个人都要罚",
    story:
      "比分 0:0。队长把球塞进你怀里，赛季主罚手却拽住你的袖口：他的续约奖金里写着“决赛进球”。四万人的嘘声压下来。",
    choices: [
      {
        eyebrow: "抢过命运",
        title: "亲自主罚",
        copy: "把奖杯、奖金和骂名都押在自己脚下。",
        impact: "名气 ↑↑↑ · 信任 ↓",
        effects: { ovr: 3, energy: -7, reputation: 20, trust: -6, apps: 32, goals: 13, value: 260 },
        trophy: "海峡杯",
        note: "球贴着立柱入网。你捧起奖杯，主罚手却拒绝参加合影。",
      },
      {
        eyebrow: "照顾队友",
        title: "把球交给主罚手",
        copy: "让他保住续约，也让球队按顺序执行。",
        impact: "信任 ↑↑↑ · 名气平稳",
        effects: { trust: 18, morale: 9, apps: 33, goals: 8, assists: 10, value: 175 },
        trophy: "海峡杯",
        note: "他罚进后跪地痛哭，随后把续约奖金分给了全队工作人员。",
      },
      {
        eyebrow: "打破剧本",
        title: "把点球做成战术配合",
        copy: "轻推横传，让第二人冲进禁区射门。",
        impact: "传奇概率 · 翻车风险",
        effects: { ovr: 4, reputation: 14, morale: 5, apps: 32, goals: 9, assists: 13, value: 225 },
        trophy: "海峡杯",
        note: "全场以为你疯了。皮球入网后，这次配合被重播了整整十年。",
      },
    ],
  },
  {
    year: "2032 / 33",
    age: 22,
    kicker: "凌晨两点 · 聊天记录泄露",
    title: "你骂教练的话上了热搜",
    story:
      "你在私人群里说教练“战术像上个世纪”。截图只截了这一句，发送者正是你最信任的队友。俱乐部要求你天亮前公开道歉。",
    choices: [
      {
        eyebrow: "低头止血",
        title: "照稿道歉",
        copy: "承认冲动，不追究截图来源。",
        impact: "信任 ↑ · 士气 ↓",
        effects: { trust: 10, morale: -10, reputation: -4, apps: 27, goals: 8, assists: 9, value: 75 },
        note: "风波三天后结束。那个泄密的队友在训练中依然对你笑。",
      },
      {
        eyebrow: "同归于尽",
        title: "公开完整聊天记录",
        copy: "还原上下文，也把全队秘密一起曝光。",
        impact: "名气 ↑↑↑ · 信任 ↓↓↓",
        effects: { reputation: 23, trust: -24, morale: 3, apps: 19, goals: 7, value: 115 },
        note: "舆论站到你这边，但十二名队友联名要求俱乐部卖掉你。",
      },
      {
        eyebrow: "反客为主",
        title: "拒绝道歉，直播讲战术",
        copy: "既然话已公开，就把问题讲到底。",
        impact: "能力 ↑↑ · 出场风险",
        effects: { ovr: 3, trust: -12, reputation: 17, apps: 20, assists: 12, value: 100 },
        note: "直播变成战术公开课。教练赢了权力，你赢了同行和球迷的尊重。",
      },
    ],
  },
  {
    year: "2033 / 34",
    age: 23,
    kicker: "国家队办公室 · 两本护照",
    title: "两支国家队同时打来电话",
    story:
      "出生地国家承诺核心位置，祖籍国拥有更强阵容却只承诺考察。社交媒体已经把你撕成两半，而选择一旦生效便不能反悔。",
    choices: [
      {
        eyebrow: "归属",
        title: "代表出生地国家",
        copy: "选择养大你的城市，也选择更漫长的世界杯之路。",
        impact: "信任 ↑↑ · 名气 ↑",
        effects: { trust: 15, morale: 10, reputation: 12, apps: 31, goals: 11, assists: 8, value: 150 },
        note: "首秀国歌响起时，你没有犹豫。赛后，另一边的亲戚群沉默了。",
      },
      {
        eyebrow: "最高舞台",
        title: "代表祖籍国",
        copy: "竞争更残酷，但世界杯触手可及。",
        impact: "名气 ↑↑↑ · 信任两极化",
        effects: { ovr: 3, trust: -8, reputation: 24, apps: 25, goals: 8, assists: 7, value: 240 },
        note: "你在嘘声中完成首秀。那晚，两面国旗都出现在看台上。",
      },
      {
        eyebrow: "拒绝归类",
        title: "暂不选择任何一边",
        copy: "要求媒体停止替你定义身份。",
        impact: "士气 ↑ · 国家队机会 ↓",
        effects: { morale: 14, reputation: 8, trust: -4, apps: 29, goals: 10, assists: 9, value: 100 },
        note: "你换来一年安静，也让两边主帅都开始准备没有你的方案。",
      },
    ],
  },
  {
    year: "2034 / 35",
    age: 24,
    kicker: "转会窗最后六小时",
    title: "死敌把违约金打到了账上",
    story:
      "对面那支球队刚在德比中羞辱过你的家人，如今愿意给你三倍工资。老东家突然拿出一份早已承诺却从未兑现的新合同。",
    choices: [
      {
        eyebrow: "职业无罪",
        title: "接受死敌的三倍薪资",
        copy: "足球是工作，忠诚不能替你支付未来。",
        impact: "身价 ↑↑↑ · 信任 ↓↓↓",
        effects: { ovr: 4, trust: -24, reputation: 20, morale: -5, apps: 34, goals: 14, assists: 10, value: 620 },
        note: "亮相仪式外有人烧掉你的旧球衣。三个月后，你在德比进球却没有庆祝。",
      },
      {
        eyebrow: "忠诚定价",
        title: "留队并公开所有报价",
        copy: "让球迷知道你放弃了多少钱。",
        impact: "信任 ↑↑↑ · 管理层关系 ↓",
        effects: { trust: 24, reputation: 10, morale: 10, apps: 38, goals: 16, assists: 12, value: 350 },
        note: "主场制作了你的巨幅画像。管理层则从此不再让你看到完整财务数字。",
      },
      {
        eyebrow: "第三条路",
        title: "当天飞往第三家俱乐部",
        copy: "避开内战，去完全陌生的联赛。",
        impact: "能力 ↑↑ · 体能 ↓",
        effects: { ovr: 5, energy: -10, reputation: 17, apps: 33, goals: 13, assists: 11, value: 510 },
        note: "机场没有发布会，只有一名举错名字牌的司机。你从零开始。",
      },
    ],
  },
  {
    year: "2035 / 36",
    age: 25,
    kicker: "世界杯预选赛 · 生死战",
    title: "母亲的手术和比赛在同一天",
    story:
      "主帅说国家队离世界杯只差一场，家人说手术风险不高，但母亲在电话里沉默了很久。两座城市相隔九千公里。",
    choices: [
      {
        eyebrow: "国家使命",
        title: "留在首发名单",
        copy: "把手机交给队医，九十分钟后再听消息。",
        impact: "名气 ↑↑↑ · 士气风险",
        effects: { reputation: 22, morale: -12, energy: -8, apps: 36, goals: 14, assists: 9, value: 330 },
        trophy: "世界杯入场券",
        note: "你助攻绝杀，国家晋级。庆典中，妹妹发来一句：手术成功，她问你赢了吗。",
      },
      {
        eyebrow: "家人在前",
        title: "连夜飞回医院",
        copy: "有些比赛可以重来，有些告别不行。",
        impact: "士气 ↑↑↑ · 名气 ↓",
        effects: { morale: 22, trust: -8, reputation: -7, apps: 25, goals: 7, assists: 7, value: -80 },
        note: "国家队输掉比赛。母亲醒来时握住你的手：至少这一场，我赢了。",
      },
      {
        eyebrow: "两边都不放",
        title: "比赛前全程视频连线",
        copy: "留队，但把战术会和热身全部压缩。",
        impact: "体能 ↓ · 信任 ↑",
        effects: { energy: -12, trust: 8, morale: 8, apps: 33, goals: 10, assists: 11, value: 160 },
        note: "你状态并不好，却在最后时刻制造点球。病房和球场同时爆发欢呼。",
      },
    ],
  },
  {
    year: "2036 / 37",
    age: 26,
    kicker: "药检报告 · 队友的名字",
    title: "冠军队友承认用了禁药",
    story:
      "他是你最好的朋友，也是决赛唯一进球者。他说药是队医给的，求你帮忙统一口径。明早调查组会逐个问话。",
    choices: [
      {
        eyebrow: "保护朋友",
        title: "按他的版本作证",
        copy: "把责任推给已经离职的队医。",
        impact: "信任 ↑↑ · 清白风险",
        effects: { trust: 18, morale: -8, reputation: -10, apps: 31, goals: 10, value: -90 },
        trophy: "争议联赛冠军",
        note: "奖杯保住了。两年后新证据出现，你每次采访都要重新回答同一个问题。",
      },
      {
        eyebrow: "说出真相",
        title: "提交聊天记录",
        copy: "冠军可能被剥夺，友谊也会结束。",
        impact: "名气 ↑ · 信任 ↓↓",
        effects: { trust: -18, reputation: 18, morale: -5, apps: 29, goals: 9, assists: 10, value: 70 },
        note: "冠军被撤销，朋友禁赛四年：你是对的，但我永远不会原谅你。",
      },
      {
        eyebrow: "追到源头",
        title: "要求调查整套医疗体系",
        copy: "不替任何人顶罪，也不让球员独自承担。",
        impact: "信任 ↑ · 管理层震荡",
        effects: { ovr: 2, trust: 6, reputation: 16, energy: -6, apps: 30, assists: 11, value: 95 },
        note: "调查牵出三家俱乐部。联赛从此建立了独立医疗审查。",
      },
    ],
  },
  {
    year: "2037 / 38",
    age: 27,
    kicker: "欧战半决赛前 · 匿名邮件",
    title: "有人用你的家人勒索你退赛",
    story:
      "邮件附着家人的私人影像：只要你明晚不上场，一切就不会公开。警方无法保证在开球前找到发件人。",
    choices: [
      {
        eyebrow: "封锁消息",
        title: "独自承受，照常首发",
        copy: "不告诉家人，不让任何人打乱比赛。",
        impact: "名气 ↑↑ · 士气 ↓↓↓",
        effects: { reputation: 17, morale: -24, energy: -10, apps: 35, goals: 12, assists: 10, value: 240 },
        note: "你打进制胜球，影像也在终场后被公开。家人最难接受的是你没有提前告诉他们。",
      },
      {
        eyebrow: "夺回叙事",
        title: "全家共同公开事件",
        copy: "让勒索者失去手里的秘密。",
        impact: "信任 ↑↑↑ · 隐私归零",
        effects: { trust: 22, reputation: 20, morale: 8, apps: 34, goals: 10, assists: 12, value: 280 },
        note: "发布会没有一个人低头。第二天，你带着全场掌声走进球场。",
      },
      {
        eyebrow: "设下陷阱",
        title: "假装退赛，配合警方追踪",
        copy: "牺牲赛前准备，赌一次抓现行。",
        impact: "体能 ↓↓ · 名气 ↑",
        effects: { energy: -18, reputation: 13, trust: 10, apps: 27, goals: 7, assists: 9, value: 120 },
        note: "发件人在酒店被捕。你替补登场时已是第 70 分钟，球队最终止步半决赛。",
      },
    ],
  },
  {
    year: "2038 / 39",
    age: 28,
    kicker: "检查室的白灯",
    title: "膝盖里传来撕裂声",
    story:
      "医生说手术会缺席九个月；打封闭可以赶上争冠，但下一次可能直接结束职业生涯。俱乐部合同只剩一年。",
    choices: [
      {
        eyebrow: "长期主义",
        title: "立刻手术",
        copy: "错过争冠，换取职业生命。",
        impact: "体能 ↑↑ · 身价 ↓↓",
        effects: { energy: 20, morale: -9, reputation: -6, apps: 8, goals: 2, assists: 2, value: -220 },
        note: "康复像一场没有观众的比赛。俱乐部没有续约，但你重新学会了全速奔跑。",
      },
      {
        eyebrow: "冠军窗口",
        title: "打封闭，坚持八轮",
        copy: "奖杯就在眼前，未来可以以后再说。",
        impact: "冠军 ↑ · 体能 ↓↓↓",
        effects: { ovr: 2, energy: -28, reputation: 13, apps: 30, goals: 11, assists: 7, value: 140 },
        trophy: "全国联赛冠军",
        note: "你撑过最后八轮并捧杯。庆典之后，走下三层台阶都需要人扶。",
      },
      {
        eyebrow: "重写位置",
        title: "拒绝手术，后撤组织",
        copy: "少冲刺，用视野换时间。",
        impact: "能力 ↑↑ · 助攻 ↑↑",
        effects: { ovr: 4, energy: -10, trust: 12, apps: 26, goals: 4, assists: 16, value: 80 },
        note: "你失去了速度，却第一次真正看清整片球场。",
      },
    ],
  },
  {
    year: "2039 / 40",
    age: 29,
    kicker: "复出发布会 · 主帅的新名单",
    title: "你的号码穿在新人身上",
    story:
      "你康复归队，发现 10 号已经给了十九岁天才。主帅说你可以留下“帮助年轻人”，经纪人则带来一份降级队主力合同。",
    choices: [
      {
        eyebrow: "夺回一切",
        title: "留下竞争 10 号",
        copy: "把每次训练都踢成决赛。",
        impact: "能力 ↑↑ · 士气风险",
        effects: { ovr: 4, energy: -16, morale: 5, apps: 23, goals: 8, assists: 9, value: 90 },
        note: "你没有拿回号码，却和那名新人同时进入了赛季最佳阵容。",
      },
      {
        eyebrow: "尊严转身",
        title: "加盟一支降级区球队",
        copy: "从冠军竞争者变成保级队长。",
        impact: "信任 ↑↑↑ · 名气 ↓",
        effects: { trust: 22, reputation: -6, morale: 12, apps: 36, goals: 11, assists: 12, value: -40 },
        note: "最后一轮保级成功时，五万人冲进球场。你第一次知道保级也可以像夺冠。",
      },
      {
        eyebrow: "传承不是投降",
        title: "主动辅导新人",
        copy: "把号码让出去，把比赛理解留下来。",
        impact: "信任 ↑↑ · 助攻 ↑",
        effects: { trust: 18, ovr: 2, morale: 9, apps: 25, goals: 5, assists: 15, value: 35 },
        note: "新人领奖时公开感谢你。第二天，主帅把队长袖标放进你的柜子。",
      },
    ],
  },
  {
    year: "2040 / 41",
    age: 30,
    kicker: "世界杯八强 · 点球大战",
    title: "全国都在等你走向罚球点",
    story:
      "你是队长，却在训练中连续罚丢三次。年轻前锋悄悄说他状态很好，主帅只问：第五个，你来不来？",
    choices: [
      {
        eyebrow: "队长承担",
        title: "主罚第五个",
        copy: "英雄或罪人，不把命运交给别人。",
        impact: "传奇 ↑↑↑ · 士气风险",
        effects: { reputation: 26, energy: -10, morale: 6, apps: 34, goals: 13, assists: 8, value: 260 },
        trophy: "世界杯四强",
        note: "你没有看门将，球飞进左上角。那一夜，全城没有人睡。",
      },
      {
        eyebrow: "相信状态",
        title: "让年轻前锋主罚",
        copy: "袖标不是垄断英雄时刻的许可证。",
        impact: "信任 ↑↑↑ · 名气平稳",
        effects: { trust: 24, morale: 12, apps: 34, goals: 9, assists: 12, value: 170 },
        trophy: "世界杯四强",
        note: "他罚进后冲向你。十年后他说，那是改变一生的信任。",
      },
      {
        eyebrow: "心理战",
        title: "主动改罚第一个",
        copy: "先稳定全队，再把第五个留给年轻人。",
        impact: "能力 ↑ · 信任 ↑↑",
        effects: { ovr: 3, trust: 16, reputation: 18, apps: 35, goals: 11, assists: 10, value: 210 },
        trophy: "世界杯四强",
        note: "你第一个罚进，他最后一个终结比赛。两代人一起登上头版。",
      },
    ],
  },
  {
    year: "2041 / 42",
    age: 31,
    kicker: "俱乐部工资拖欠 14 周",
    title: "老板要全队假装一切正常",
    story:
      "财务即将崩盘。老板承诺只要你作为队长公开否认欠薪，就先付你的工资。年轻球员已经交不起房租。",
    choices: [
      {
        eyebrow: "保护自己",
        title: "接受秘密付款",
        copy: "职业生涯不长，你也有家庭要养。",
        impact: "财富 ↑↑ · 信任 ↓↓↓",
        effects: { trust: -28, morale: -10, reputation: -12, apps: 28, goals: 8, value: 160 },
        note: "你的账户到账了。两周后记录泄露，队友在客场大巴上拒绝让你上车。",
      },
      {
        eyebrow: "集体行动",
        title: "带队拒绝出场",
        copy: "宁愿判负，也不让最年轻的人独自承担。",
        impact: "信任 ↑↑↑ · 身价 ↓",
        effects: { trust: 28, reputation: 14, morale: 10, apps: 21, goals: 5, value: -120 },
        note: "比赛取消，联赛介入托管。球迷第一次为一场没有开球的比赛鼓掌。",
      },
      {
        eyebrow: "引爆证据",
        title: "把账本交给记者",
        copy: "不罢赛，直接掀开财务黑洞。",
        impact: "名气 ↑↑ · 管理层崩塌",
        effects: { reputation: 21, trust: 12, energy: -9, apps: 30, goals: 7, assists: 11, value: 30 },
        note: "老板被调查，俱乐部扣分。你们用最后十轮把球队拖出降级区。",
      },
    ],
  },
  {
    year: "2042 / 43",
    age: 32,
    kicker: "队长袖标 · 更衣室兵变",
    title: "年轻核心要求主帅下课",
    story:
      "一半队友准备抵制训练，另一半担心合同违约。主帅曾在你低谷时救过你，但他的战术确实失去了所有人。",
    choices: [
      {
        eyebrow: "忠于恩人",
        title: "公开支持主帅",
        copy: "在所有人离开时站到他身边。",
        impact: "信任分裂 · 出场 ↑",
        effects: { trust: -12, morale: -8, reputation: 8, apps: 33, goals: 9, assists: 9, value: 20 },
        note: "主帅三周后下课。新教练的第一件事，是把你移出队长名单。",
      },
      {
        eyebrow: "顺应更衣室",
        title: "签下联名信",
        copy: "个人恩情不能高于整支球队。",
        impact: "信任 ↑↑ · 名气风险",
        effects: { trust: 18, morale: 12, reputation: 10, apps: 31, goals: 8, assists: 12, value: 55 },
        note: "主帅离开时只和你握手：我救过你一次，你今天救了这支队一次。",
      },
      {
        eyebrow: "最后调停",
        title: "锁门开一场通宵会议",
        copy: "没人离开，直到每个人把话说完。",
        impact: "体能 ↓ · 信任 ↑↑↑",
        effects: { energy: -12, trust: 24, morale: 14, apps: 32, goals: 7, assists: 13, value: 60 },
        trophy: "足总杯",
        note: "没有人真正满意，但所有人重新训练。五个月后，你们一起捧起足总杯。",
      },
    ],
  },
  {
    year: "2043 / 44",
    age: 33,
    kicker: "酒店停车场 · 黑色信封",
    title: "有人要你们“少赢一个球”",
    story:
      "陌生人准确说出你家人的住址，并承诺一笔足以退休的钱。要求很简单：明晚可以赢，但不能赢两个以上。",
    choices: [
      {
        eyebrow: "零容忍",
        title: "立刻报警并报告联赛",
        copy: "让比赛进入监控，也让家人接受保护。",
        impact: "清白 ↑↑↑ · 家庭压力 ↑",
        effects: { reputation: 18, trust: 15, morale: -7, apps: 29, goals: 7, assists: 10, value: 45 },
        note: "警方在看台抓到两人。你们赢了 3:0，每个进球都像一次公开回答。",
      },
      {
        eyebrow: "危险反间",
        title: "假装答应，协助取证",
        copy: "继续联系，直到资金链露出水面。",
        impact: "名气 ↑↑ · 体能 ↓↓",
        effects: { reputation: 24, energy: -18, trust: 8, apps: 25, goals: 5, value: 70 },
        note: "调查持续四个月，抓出跨联赛团伙。你的电话从此不敢开陌生来电。",
      },
      {
        eyebrow: "沉默躲开",
        title: "不上报，申请轮休",
        copy: "不收钱也不涉险，把威胁留在黑暗里。",
        impact: "清白保留 · 士气 ↓↓↓",
        effects: { morale: -22, trust: -8, reputation: -5, apps: 19, goals: 3, value: -70 },
        note: "球队恰好只赢一球。没人能证明什么，但你知道沉默替谁完成了任务。",
      },
    ],
  },
  {
    year: "2044 / 45",
    age: 34,
    kicker: "青训球员的录音",
    title: "功勋助教长期羞辱年轻人",
    story:
      "十八岁门将发来录音：辱骂、威胁、强迫带伤训练。助教是俱乐部传奇，也是当年把你带进一线队的人。",
    choices: [
      {
        eyebrow: "公开站出来",
        title: "陪年轻人召开发布会",
        copy: "让他不必独自面对传奇与俱乐部。",
        impact: "信任 ↑↑↑ · 旧情断裂",
        effects: { trust: 25, reputation: 20, morale: 6, apps: 27, goals: 6, assists: 9, value: 20 },
        note: "助教停职，更多年轻人开始作证。他离开基地前只说：我看错了你。",
      },
      {
        eyebrow: "内部解决",
        title: "拿录音逼助教辞职",
        copy: "保护年轻人，也避免公开摧毁一个人。",
        impact: "信任 ↑↑ · 名气平稳",
        effects: { trust: 16, morale: 10, reputation: 6, apps: 29, goals: 7, assists: 10, value: 30 },
        note: "助教以健康原因辞职。制度没有改变，但那名门将终于睡了一个完整的夜晚。",
      },
      {
        eyebrow: "拒绝介入",
        title: "让他走正式投诉流程",
        copy: "你不是法官，不想用个人声望替代程序。",
        impact: "信任 ↓↓ · 专注比赛",
        effects: { ovr: 2, trust: -18, morale: -5, apps: 32, goals: 8, assists: 11, value: 45 },
        note: "投诉因证据不足被驳回。半年后，那名门将离开足球，也不再回复你。",
      },
    ],
  },
  {
    year: "2045 / 46",
    age: 35,
    kicker: "最后的大合同",
    title: "三条路，没有一条体面",
    story:
      "母队要你降薪七成做替补，新大陆球队给出职业生涯最高年薪，电视台则希望你立刻退役，并承诺黄金档主持席。",
    choices: [
      {
        eyebrow: "留在球场",
        title: "降薪留队",
        copy: "接受替补身份，把最后的经验留给这里。",
        impact: "信任 ↑↑↑ · 身价 ↓",
        effects: { trust: 24, morale: 7, apps: 20, goals: 4, assists: 8, value: -180 },
        note: "你很少首发，却成了每个年轻球员进场前最后拥抱的人。",
      },
      {
        eyebrow: "兑现价值",
        title: "签约新大陆球队",
        copy: "离开熟悉的一切，再赚最后一份大合同。",
        impact: "财富 ↑↑↑ · 体能 ↓",
        effects: { energy: -12, reputation: 12, apps: 28, goals: 9, assists: 7, value: 260 },
        note: "海风、塑料草皮和陌生看台。你重新变回一个需要证明自己的新援。",
      },
      {
        eyebrow: "提前转身",
        title: "签下球员兼助教合同",
        copy: "减少出场，把经验变成另一种竞争力。",
        impact: "健康 ↑↑ · 信任 ↑↑",
        effects: { energy: 18, morale: 9, reputation: 10, trust: 15, apps: 12, assists: 4, value: -60 },
        note: "你第一次站在战术板前讲话。年轻人认真听着，而替补名单上仍有你的名字。",
      },
    ],
  },
  {
    year: "2046 / 47",
    age: 36,
    kicker: "合同到期日 · 俱乐部提前办了告别",
    title: "所有人都替你决定该退役了",
    story:
      "俱乐部发布了你的告别海报，甚至没先问你。主帅说这是最体面的结局，但体检报告显示，你仍能踢完整个赛季。",
    choices: [
      {
        eyebrow: "逼他决定",
        title: "撕掉海报要求续约",
        copy: "公开告诉所有人，你的生涯只能由自己结束。",
        impact: "名气 ↑↑↑ · 信任 ↓",
        effects: { reputation: 25, trust: -12, morale: 15, apps: 18, goals: 5, value: -40 },
        note: "舆论逼俱乐部给出一年合同。你留下了，却必须和最不想留下你的主帅共处。",
      },
      {
        eyebrow: "尊重比赛",
        title: "接受告别，再去低级别联赛",
        copy: "把掌声留给这里，把下一年留给自己。",
        impact: "信任 ↑↑ · 名气 ↓",
        effects: { trust: 18, morale: 9, reputation: -5, energy: 4, apps: 25, goals: 8, value: -70 },
        note: "你含泪绕场一周，第二天却出现在另一座小球场的体检室。",
      },
      {
        eyebrow: "夺回告别",
        title: "拒绝仪式并成为自由球员",
        copy: "没有合同、没有保证，只保留继续比赛的可能。",
        impact: "自由 ↑↑ · 风险 ↑↑",
        effects: { morale: 18, reputation: 12, trust: -6, energy: 7, value: -90 },
        note: "告别夜没有出现你的身影。凌晨，你独自在训练场做完了全部体能测试。",
      },
    ],
  },
  {
    year: "2047 / 48",
    age: 37,
    kicker: "冬窗最后一天 · 没有一份正式报价",
    title: "经纪人让你参加公开试训",
    story:
      "三百名观众举着手机，和你一起试训的球员最年轻只有 18 岁。经纪人说，这是继续职业生涯唯一的门；评论区却已经把它叫作“传奇受辱现场”。",
    choices: [
      {
        eyebrow: "吞下骄傲",
        title: "穿上无号码训练服",
        copy: "让双脚回答年龄，而不是让履历回答。",
        impact: "能力 ↑ · 名气 ↓",
        effects: { ovr: 2, morale: -5, reputation: -8, energy: -10, apps: 20, goals: 6, value: 35 },
        note: "你在对抗赛送出三次助攻。试训结束时，18 岁的孩子们排队找你签名。",
      },
      {
        eyebrow: "自己制造机会",
        title: "直播全部体测数据",
        copy: "把俱乐部不愿承担的判断交给公众。",
        impact: "名气 ↑↑↑ · 争议 ↑",
        effects: { reputation: 22, morale: 8, trust: -6, energy: -8, apps: 17, goals: 5, value: 55 },
        note: "直播观看破百万。俱乐部在舆论压力下签你，却把“商业价值”写进了合同。",
      },
      {
        eyebrow: "改变赛道",
        title: "加盟半职业家乡队",
        copy: "不再追逐聚光灯，只追逐每周末的比赛。",
        impact: "快乐 ↑↑↑ · 身价 ↓",
        effects: { morale: 20, trust: 16, reputation: -10, energy: 5, apps: 28, goals: 12, assists: 9, value: -80 },
        note: "球场只有两千个座位，却场场坐满。卖票的大叔还记得你十四岁时的样子。",
      },
    ],
  },
  {
    year: "2048 / 49",
    age: 38,
    kicker: "杯赛半决赛前夜 · 全队拒绝训练",
    title: "年轻球员决定罢赛",
    story:
      "俱乐部拖欠青年球员四个月工资，却按时付清了你的高额奖金。队友推你做罢赛代表，老板则警告：比赛取消，所有人都可能失业。",
    choices: [
      {
        eyebrow: "站到最前面",
        title: "以队长身份宣布罢赛",
        copy: "用自己的名气替没有话语权的人承担后果。",
        impact: "信任 ↑↑↑ · 奖杯风险",
        effects: { trust: 28, reputation: 17, morale: 12, apps: -1, value: -90 },
        note: "比赛被判负，老板被迫结清欠薪。更衣室把那天称作你真正赢下的半决赛。",
      },
      {
        eyebrow: "先踢再谈",
        title: "说服全队完成比赛",
        copy: "承诺晋级奖金全部分给被欠薪的年轻人。",
        impact: "奖杯 ↑ · 财富 ↓",
        effects: { trust: 18, morale: 8, energy: -12, apps: 5, goals: 2, assists: 2, value: -120 },
        trophy: "山海杯",
        note: "你们逆转晋级并最终夺冠。领奖台上，年轻人把奖杯先递给了食堂阿姨。",
      },
      {
        eyebrow: "秘密谈判",
        title: "录下老板的威胁",
        copy: "表面维持比赛，背后把证据交给球员工会。",
        impact: "名气 ↑↑ · 信任风险",
        effects: { reputation: 20, trust: 6, morale: -5, apps: 4, assists: 3, value: -50 },
        note: "录音引发足坛地震。老板被调查，而有人开始追问录音究竟是谁泄露的。",
      },
    ],
  },
  {
    year: "2049 / 50",
    age: 39,
    kicker: "纪录片首映礼 · 未剪辑片段流出",
    title: "主帅说你早该退役",
    story:
      "镜头拍到主帅私下说，留下你只是俱乐部的营销决定。三小时后你们要一起出席发布会，门外已经挤满记者。",
    choices: [
      {
        eyebrow: "当场拆穿",
        title: "发布会上播放原片",
        copy: "让主帅在所有镜头前解释自己的话。",
        impact: "名气 ↑↑↑ · 信任 ↓↓",
        effects: { reputation: 25, trust: -18, morale: 10, apps: 12, goals: 3, value: -40 },
        note: "发布会变成公开决裂。主帅一周后下课，你也失去了最稳定的出场保证。",
      },
      {
        eyebrow: "用比赛回答",
        title: "坐在他身边保持沉默",
        copy: "把所有愤怒留到周末的首发名单。",
        impact: "能力 ↑↑ · 压力 ↑",
        effects: { ovr: 3, energy: -14, morale: 6, trust: 8, apps: 24, goals: 10, assists: 7, value: 20 },
        note: "你连续五场进球。第六场前，主帅亲手把队长袖标递给了你。",
      },
      {
        eyebrow: "揭开行业",
        title: "把纪录片改成老将生存调查",
        copy: "不再纠缠一句话，去追问年龄歧视如何决定合同。",
        impact: "影响力 ↑↑↑ · 球场数据 ↓",
        effects: { reputation: 24, trust: 15, morale: 12, apps: 10, assists: 4, value: -60 },
        note: "纪录片拿下年度大奖。很多无名老将第一次在镜头前讲完自己的故事。",
      },
    ],
  },
  {
    year: "2050 / 51",
    age: 40,
    kicker: "国家队凌晨来电 · 世界杯名单截止前六小时",
    title: "医生发现一次异常心跳",
    story:
      "国家队因伤病潮希望你紧急复出，但体检捕捉到一次无法解释的心律异常。医生说大概率无事，也无法保证高强度比赛绝对安全。",
    choices: [
      {
        eyebrow: "最后一次豪赌",
        title: "签下风险告知书",
        copy: "穿上国家队球衣，接受身体可能给出的任何答案。",
        impact: "传奇 ↑↑↑ · 健康 ↓↓",
        effects: { reputation: 30, energy: -24, morale: 14, apps: 6, goals: 2, assists: 2, value: 20 },
        trophy: "洲际冠军",
        note: "你在决赛加时送出制胜助攻。终场哨响后，你先摸了摸胸口，才举起双手。",
      },
      {
        eyebrow: "选择活着",
        title: "拒绝征召并公开报告",
        copy: "承认恐惧，也提醒所有球员体检不是走过场。",
        impact: "健康 ↑↑↑ · 名气 ↑",
        effects: { energy: 24, morale: 7, trust: 18, reputation: 12, apps: 10, value: -80 },
        note: "有人骂你临阵退缩，更多年轻球员开始主动要求完整心脏筛查。",
      },
      {
        eyebrow: "换一种方式参赛",
        title: "作为更衣室顾问随队",
        copy: "不进入名单，但把四十年的经验留在队内。",
        impact: "信任 ↑↑↑ · 荣耀共享",
        effects: { trust: 26, reputation: 18, morale: 16, energy: 10, apps: 0, value: -50 },
        trophy: "洲际冠军",
        note: "决赛点球大战前，你逐个拥抱罚球队员。冠军合影里，你站在最边上，却没人忘记你。",
      },
    ],
  },
  {
    year: "2051 / 52",
    age: 41,
    kicker: "保级决战前三天 · 俱乐部账户被冻结",
    title: "老板要你替一枚空气币站台",
    story:
      "老板承诺，只要你公开宣传俱乐部发行的数字代币，就能立刻支付全队工资。财务主管私下告诉你，这笔钱很可能来自下一批球迷。",
    choices: [
      {
        eyebrow: "救眼前的人",
        title: "代言并把报酬分给全队",
        copy: "先让工作人员拿到工资，再承担未来的骂名。",
        impact: "信任 ↑ · 名气风险",
        effects: { trust: 12, morale: 10, reputation: -12, apps: 15, goals: 4, value: 80 },
        note: "工资到账了，代币却在一个月后归零。受损球迷举着你的海报来到训练基地。",
      },
      {
        eyebrow: "彻底揭穿",
        title: "把合同交给金融调查记者",
        copy: "宁可俱乐部立刻崩塌，也不让骗局继续。",
        impact: "名气 ↑↑↑ · 俱乐部危机",
        effects: { reputation: 27, trust: 15, morale: -12, apps: 10, value: -100 },
        note: "老板被带走，球队被托管。你失去合同，却阻止了更多球迷把积蓄投进去。",
      },
      {
        eyebrow: "自己接管",
        title: "组织球员与球迷众筹持股",
        copy: "把俱乐部从一个老板的玩具变成共同资产。",
        impact: "信任 ↑↑↑ · 财富 ↓↓",
        effects: { trust: 30, reputation: 22, morale: 16, energy: -10, apps: 14, assists: 5, value: -180 },
        note: "众筹在最后一小时达标。你同时成了球员、小股东和每场会议最后离开的人。",
      },
    ],
  },
  {
    year: "2052 / 53",
    age: 42,
    kicker: "第 93 分钟 · 保级生死战",
    title: "一个不存在的点球，决定所有人的命运",
    story:
      "比分 1:1，球队必须取胜才能保级。裁判判给你们一个明显误判的点球，18 岁新人刚因失误丢球，哭着求你把球交给他完成救赎。",
    choices: [
      {
        eyebrow: "传奇亲自收尾",
        title: "抱紧足球走向十二码",
        copy: "把整家俱乐部和自己的最后一脚都扛在肩上。",
        impact: "传奇 ↑↑↑ · 压力封顶",
        effects: { reputation: 30, morale: 20, energy: -18, apps: 1, goals: 1, value: -100 },
        trophy: "保级奇迹",
        note: "球钻进死角。你没有庆祝，只跪下来亲吻草皮——这一次，真的没有下一场了。",
      },
      {
        eyebrow: "把未来交出去",
        title: "把点球递给 18 岁新人",
        copy: "你的故事已经足够长，他的故事才刚开始。",
        impact: "信任 ↑↑↑ · 结局未知",
        effects: { trust: 32, reputation: 24, morale: 16, apps: 1, assists: 1, value: -100 },
        trophy: "保级奇迹",
        note: "他罚进后第一个冲向你。多年以后，他说自己的职业生涯从你递出足球那一刻开始。",
      },
      {
        eyebrow: "尊重比赛",
        title: "告诉裁判这不是犯规",
        copy: "用保级和最后一场，交换一个不会后悔的决定。",
        impact: "尊重 ↑↑↑ · 球队降级",
        effects: { trust: 28, reputation: 32, morale: -8, apps: 1, value: -100 },
        note: "裁判取消点球，球队最终降级。客队球迷却和主队球迷一起站起来，为你鼓掌到灯光熄灭。",
      },
    ],
  },
];
